### ISSUE TITLE
Space-less Output

### ISSUE THREAD

**Issue by utpalsavliya** [tusharjain88954/Tushar-jain#5]
Commit ea128b80b4e681a51f859aa264268b44fabb3d7d removed the whitespaces from the output. Running the test cases, we see that  sometimes it becomes difficult to understand the different operands, as all appear bunched together in the output.
I suggest reverting back to commit 17963cca99c882c6dab71e0e75948f24366cef0b or to merge it with the present commit, and closing this issue if it doesn't seem to be a problem.

**Comment by tusharjain88954** [comment]
@utpalsavliya  i have checked all possible test-cases , there is no error.As the input is not space separated then output must not space-separated ,it sounds good.

By the way , thanks for suggesting changes , fixes bug  and beautify the code👍.```

```
